// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `fm.teal.alpha.actor` namespace.
pub mod profile;
pub mod status;
#[derive(Debug)]
pub struct Profile;
impl crate::types::Collection for Profile {
    const NSID: &'static str = "fm.teal.alpha.actor.profile";
    type Record = profile::Record;
}
#[derive(Debug)]
pub struct Status;
impl crate::types::Collection for Status {
    const NSID: &'static str = "fm.teal.alpha.actor.status";
    type Record = status::Record;
}
