// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `fm.teal.alpha.feed` namespace.
pub mod defs;
pub mod get_actor_feed;
pub mod get_play;
pub mod play;
#[derive(Debug)]
pub struct Play;
impl crate::types::Collection for Play {
    const NSID: &'static str = "fm.teal.alpha.feed.play";
    type Record = play::Record;
}
