// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `fm` namespace.
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-fmteal")))]
#[cfg(feature = "namespace-fmteal")]
pub mod teal;
