// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `fm.teal.alpha.actor.profile` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///Small image to be displayed next to posts from account. AKA, 'profile picture'
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub avatar: core::option::Option<crate::types::BlobRef>,
    ///Larger horizontal image to display behind profile view.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub banner: core::option::Option<crate::types::BlobRef>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub created_at: core::option::Option<crate::types::string::Datetime>,
    ///Free-form profile description text.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub description: core::option::Option<String>,
    ///Annotations of text in the profile description (mentions, URLs, hashtags, etc).
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub description_facets: core::option::Option<
        Vec<crate::app::bsky::richtext::facet::Main>,
    >,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub display_name: core::option::Option<String>,
    ///The user's most recent item featured on their profile.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub featured_item: core::option::Option<FeaturedItem>,
}
pub type Record = crate::types::Object<RecordData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct FeaturedItemData {
    ///The Musicbrainz ID of the item
    pub mbid: String,
    ///The type of the item. Must be a valid Musicbrainz type, e.g. album, track, recording, etc.
    pub r#type: String,
}
pub type FeaturedItem = crate::types::Object<FeaturedItemData>;
