// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `fm.teal.alpha.actor.status` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    pub item: crate::fm::teal::alpha::feed::defs::PlayView,
    ///The unix timestamp of when the item was recorded
    pub time: crate::types::string::Datetime,
}
pub type Record = crate::types::Object<RecordData>;
