name: Build

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx Cadet Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg BIN_NAME=cadet \
            --tag ghcr.io/${{ github.repository_owner }}/cadet:${GITHUB_REF_NAME#refs/tags/v} \
            $(if [ "${{ github.ref_name }}" == "main" ]; then echo "--tag \
              ghcr.io/${{ github.repository_owner }}/cadet:latest"; fi) \
            --push .

      - name: Docker Buildx Satellite Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg BIN_NAME=satellite \
            --tag ghcr.io/${{ github.repository_owner }}/satellite:${GITHUB_REF_NAME#refs/tags/v} \
            $(if [ "${{ github.ref_name }}" == "main" ]; then echo "--tag \
              ghcr.io/${{ github.repository_owner }}/satellite:latest"; fi) \
            --push .
